title: SCALE
tagline: SCALE
subtitle: S-PLUS Clusters and Large-scale Environments
email: your-email@example.com
description: >-
  S-PLUS Clusters and Large-scale Environments
startyear: 2023
url: "https://splus-scale.github.io"
logo: /assets/img/scale_logo_sm.png
baseurl: ""
repository: https://github.com/splus-scale/scale-website
github: splus-scale
permalink: pretty
timezone: "America/Sao_Paulo"

disqus: splus-scale

social:
  name: SCALE
  links: 
    - https://github.com/splus-scale

paginate: 5
paginate_path: "/blog/page:num"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-scholar
  - kramdown
  - rouge

exclude:
  - "*.gemspec"
  - "package*.json"
  - "*.lock"
  - Gemfile
  - README.md
  - LICENSE.txt
  - node_modules
  - vendor
  - scripts

livereload: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:month/:slug
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
      excerpt_separator: <!--more-->
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      permalink: "/authors/:title/"
  -
    scope:
      path: ""
      type: "tagslist"
    values:
      layout: "tag"
      permalink: "/blog/tags/:title/"
  -
    scope:
      path: ""
      type: "publications"
    values:
      status: "published"
      layout: "paper"
      permalink: "/publications/:slug/"
  -
    scope:
      path: "assets/profiles"
    values:
      profile_image: true

include: ['_pages']

collections:
  pgs:
    output: true
    layout: page
    show_sidebar: true
    permalink: /:name/
  authors:
    output: true
    layout: author
  tagslist:
    output: true
    layout: tag
  publications:
    output: true
    layout: paper


scholar:
  style: the-astrophysical-journal
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: main.bib
  bibliography_template: ref

  replace_strings: true
  join_strings: true

  # details_dir: bibliography
  # details_layout: bibliography.html
  # details_link: Details

  query: "@*"